<?php

$TerjemahKata = array(
    'meja' => array(
        'Indonesia' => 'meja',
        'Malaysia' => 'meja',
        'English' => 'table',
    ),
    'bayar' => array(
        'Indonesia' => 'bayar',
        'Malaysia' => 'bayar',
        'English' => 'cash/eftpos/cc',
    ),
    'tanggal' => array(
        'Indonesia' => 'tanggal',
        'Malaysia' => 'tarikh',
        'English' => 'date',
    ),
    'kembali' => array(
        'Indonesia' => 'kembali',
        'Malaysia' => 'Baki',
        'English' => 'change',
    ),
    'terimakasih' => array(
        'Indonesia' => 'terimakasih',
        'Malaysia' => 'terimakasih',
        'English' => 'thank you',
    ),
    'ingat makan ingat tuhan' => array(
        'Indonesia' => 'ingat makan ingat tuhan',
        'Malaysia' => 'ingat makan ingat tuhan',
        'English' => 'think of food think of god',
    ),
    'kasir' => array(
        'Indonesia' => 'kasir',
        'Malaysia' => 'cashier',
        'English' => 'cashier',
    ),
    'jatuh tempo' => array(
        'Indonesia' => 'jatuh tempo',
        'Malaysia' => 'tarikh bayar',
        'English' => 'due date',
    ),
    'faktur' => array(
        'Indonesia' => 'faktur',
        'Malaysia' => 'invois',
        'English' => 'invoice',
    ),
    'trem' => array(
        'Indonesia' => 'trem',
        'Malaysia' => 'payment',
        'English' => 'payment',
    ),
    'diskon' => array(
        'Indonesia' => 'diskon',
        'Malaysia' => 'diskaun',
        'English' => 'discount',
    ),
    'ongkir' => array(
        'Indonesia' => 'ongkir',
        'Malaysia' => 'kos hantar',
        'English' => 'postal fee',
    ),
    'telepon' => array(
        'Indonesia' => 'telepon',
        'Malaysia' => 'talifon',
        'English' => 'phone',
    ),
    'no. nota' => array(
        'Indonesia' => 'no. nota',
        'Malaysia' => 'no. resit',
        'English' => 'receipt number',
    ),
    'laba' => array(
        'Indonesia' => 'laba',
        'Malaysia' => 'untung',
        'English' => 'profit',
    ),
    'yakin' => array(
        'Indonesia' => 'yakin',
        'Malaysia' => 'yakin',
        'English' => 'are you sure',
    ),
    'packing ulang' => array(
        'Indonesia' => 'packing ulang',
        'Malaysia' => 'bungkus semula',
        'English' => 'repacking',
    ),
);